# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "SimulationWorkerPy",
]

@typing.final
class SimulationWorkerPy:
    def __new__(cls) -> SimulationWorkerPy: ...
    def init(self) -> None: ...
    def test_determinism(self) -> builtins.bool: ...
    def create_car(self, export_string: builtins.str, car_id: builtins.int) -> None: ...
